apiVersion: v1
kind: Namespace
metadata:
  name: bank-app
---
apiVersion: v1
kind: Secret
metadata:
  name: bank-app-secret
  namespace: bank-app
type: Opaque
data:
  directus_api_token: R1R1UFJjX1lXazctdmZrRkZzUlBEcENTU1NfY3BseVY=
  jwt_key: dmVyeV9zZWNyZXRfa2V5
  otp_secret: MTIzNDU2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-app-configmap
  namespace: bank-app
data:
  directus_url: http://directus.directus:8055
  max_amount: "1000"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: entry-point
  namespace: bank-app
spec:
  template: 
    metadata:
      annotations:
        qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/<organization>/poliflow-test-applications/bank-app/entry-point
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: login
  namespace: bank-app
spec:
  template: 
    metadata:
      annotations:
        # features.knative.dev/queueproxy-podinfo: enabled
        qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/<organization>/poliflow-test-applications/bank-app/login
          env:
            - name: DIRECTUS_URL
              valueFrom:
                configMapKeyRef:
                  name: bank-app-configmap
                  key: directus_url
            - name: DIRECTUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: directus_api_token
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: jwt_key
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: authorization
  namespace: bank-app
  # labels: 
  #   networking.knative.dev/visibility: cluster-local
spec:
  template: 
    metadata:
      annotations:
        qpoption.knative.dev/flow-config-allowed_json_flows: | 
          [{"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "http-event-sources", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}]}]
        qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/<organization>/poliflow-test-applications/bank-app/authorization
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: jwt_key
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: verify-transaction
  namespace: bank-app
spec:
  template: 
    metadata:
      annotations:
        qpoption.knative.dev/flow-config-allowed_json_flows: | 
          [{"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "http-event-sources", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "function:knative", "value": {"operation": "authorization"}}, {"type": "data_based_switch_state", "value": {"name": "authorization-decide", "type": "switch", "dataConditions": [{"condition": "${ .\"do-verification\" == true }", "transition": "verify-transaction"}], "defaultCondition": {"transition": "result"}}}]}]
        qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/<organization>/poliflow-test-applications/bank-app/verify-transaction
          env:
            - name: DIRECTUS_URL
              valueFrom:
                configMapKeyRef:
                  name: bank-app-configmap
                  key: directus_url
            - name: DIRECTUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: directus_api_token
            - name: OTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: otp_secret
            - name: MAX_AMOUNT
              valueFrom:
                configMapKeyRef:
                  name: bank-app-configmap
                  key: max_amount
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: transaction
  namespace: bank-app
spec:
  template: 
    metadata:
      annotations:
        qpoption.knative.dev/flow-config-allowed_json_flows: | 
          [{"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "http-event-sources", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "function:knative", "value": {"operation": "authorization"}}, {"type": "data_based_switch_state", "value": {"name": "authorization-decide", "type": "switch", "dataConditions": [{"condition": "${ .\"do-verification\" == true }", "transition": "verify-transaction"}], "defaultCondition": {"transition": "result"}}}, {"type": "function:knative", "value": {"operation": "verify-transaction"}}, {"type": "data_based_switch_state", "value": {"name": "verify-transaction-decide", "type": "switch", "dataConditions": [{"condition": "${ .\"do-transaction\" == true }", "transition": "transaction"}], "defaultCondition": {"transition": "result"}}}]}]
        qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/<organization>/poliflow-test-applications/bank-app/transaction
          env:
            - name: DIRECTUS_URL
              valueFrom:
                configMapKeyRef:
                  name: bank-app-configmap
                  key: directus_url
            - name: DIRECTUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bank-app-secret
                  key: directus_api_token
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: result
  namespace: bank-app
  # labels: 
  #   networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        qpoption.knative.dev/flow-activate: enable
        qpoption.knative.dev/flow-config-allowed_json_flows: | 
          [{"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "http-event-sources", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "function:knative", "value": {"operation": "authorization"}}, {"type": "data_based_switch_state", "value": {"name": "authorization-decide", "type": "switch", "dataConditions": [{"condition": "${ .\"do-verification\" == true }", "transition": "verify-transaction"}], "defaultCondition": {"transition": "result"}}}, {"type": "function:knative", "value": {"operation": "verify-transaction"}}, {"type": "data_based_switch_state", "value": {"name": "verify-transaction-decide", "type": "switch", "dataConditions": [{"condition": "${ .\"do-transaction\" == true }", "transition": "transaction"}], "defaultCondition": {"transition": "result"}}}, {"type": "function:knative", "value": {"operation": "transaction"}}]}, {"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "http-event-sources", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "function:knative", "value": {"operation": "authorization"}}, {"type": "data_based_switch_state", "value": {"name": "authorization-decide", "type": "switch", "dataConditions": [{"condition": "${ .\"do-verification\" == true }", "transition": "verify-transaction"}], "defaultCondition": {"transition": "result"}}}]}, {"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "http-event-sources", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "function:knative", "value": {"operation": "authorization"}}, {"type": "data_based_switch_state", "value": {"name": "authorization-decide", "type": "switch", "dataConditions": [{"condition": "${ .\"do-verification\" == true }", "transition": "verify-transaction"}], "defaultCondition": {"transition": "result"}}}, {"type": "function:knative", "value": {"operation": "verify-transaction"}}, {"type": "data_based_switch_state", "value": {"name": "verify-transaction-decide", "type": "switch", "dataConditions": [{"condition": "${ .\"do-transaction\" == true }", "transition": "transaction"}], "defaultCondition": {"transition": "result"}}}]}]
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
    spec:
      containers:
        - image: ghcr.io/<organization>/poliflow-test-applications/bank-app/result
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  generation: 1
  name: bind-entry-point
  namespace: bank-app
spec:
  sink: 
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker
      namespace: bank-app
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: entry-point
    namespace: bank-app
