---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-conditional-account
  namespace: simple-conditional
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: simple-conditional-account
  name: simple-conditional-account.service-account-token
  namespace: simple-conditional
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: simple-conditional-role
  namespace: simple-conditional
rules:
  # - apiGroups:
  #     - argoproj.io
  #   resources:
  #     - workflowtaskresults
  #   verbs:
  #     - create
  #     - patch
  - apiGroups:
    - argoproj.io
    resources:
    - workflowtasksets
    - workflowtaskresults
    - workflowtasksets/status
    # - workflowartifactgctasks
    verbs:
    - create
    - get
    - list
    - watch
    - delete
    - patch
    - update
  # - apiGroups:
  #   - argoproj.io
  #   resources:
  #   - workflowtasksets/status
  #   verbs:
  #   - update
  #   - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: simple-conditional-rolebinding
  namespace: simple-conditional
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: simple-conditional-role
subjects:
- kind: ServiceAccount
  name: simple-conditional-account
  namespace: simple-conditional
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: simple-conditional-workflow
  namespace: simple-conditional
spec:
  serviceAccountName: simple-conditional-account
  entrypoint: knative-conditional
  templates:
    - name: knative-conditional
      steps:
        - - name: function-a
            template: function-a-template
        - - name: function-b
            template: function-b-template
            when: "{{=jsonpath(steps['function-a'].outputs.result, '$.value')}} == true"
            # depends: "function-a.Succeeded"
          - name: function-c
            template: function-c-template
            when: "{{=jsonpath(steps['function-a'].outputs.result, '$.value')}} == false"
            # depends: "function-a.Succeeded"
    - name: function-a-template
      http:
        url: http://function-a.simple-conditional.svc.cluster.local?value=true
        method: GET
    - name: function-b-template
      http:
        url: http://function-b.simple-conditional.svc.cluster.local
        method: GET
    - name: function-c-template
      http:
        url: http://function-c.simple-conditional.svc.cluster.local
        method: GET
