apiVersion: v1
kind: Namespace
metadata:
  name: directus
---
apiVersion: v1
kind: Secret
metadata:
  name: directus-secret
  namespace: directus
type: Opaque
data:
  # Replace with your MySQL credentials (base64 encoded)
  DB_PASSWORD: b2xhYWRldXM=  # olaadeus
  DB_USER: cm9vdA==           # root
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: directus-pv
  namespace: directus
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/directus"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: directus-pvc
  namespace: directus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: directus
  namespace: directus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: directus
  template:
    metadata:
      labels:
        app: directus
    spec:
      containers:
        - name: directus
          image: directus/directus:11.9.3
          env:
            - name: DB_CLIENT
              value: mysql
            - name: DB_DATABASE
              value: test
            - name: DB_HOST
              value: mysql.mysql.svc.cluster.local  # Replace with MySQL service hostname
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: directus-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: directus-secret
                  key: DB_PASSWORD
            - name: ADMIN_EMAIL
              value: admin@example.com
            - name: ADMIN_PASSWORD
              value: password123
          volumeMounts:
            - name: directus-persistent-storage
              mountPath: /directus/data
      volumes:
        - name: directus-persistent-storage
          persistentVolumeClaim:
            claimName: directus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: directus
  namespace: directus
spec:
  type: NodePort  # Exposes the service on a port on each Node
  ports:
    - port: 8055  # The port the Directus container listens on
      targetPort: 8055  # The same port inside the container
      nodePort: 30000  # The port on each node that you can access
  selector:
    app: directus
