apiVersion: v1
kind: Namespace
metadata:
  name: refund
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: entry-point
  namespace: refund
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
    spec:
      containers:
        - image: ghcr.io/<organization>/poliflow-test-applications/refund/entry-point
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: f1
  namespace: refund
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
        # qpoption.knative.dev/flow-config-allowed_json_flows: | 
        #   [{"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "data_based_switch_state", "value": {"name": "entry-decision", "type": "switch", "dataConditions": [{"condition": "${ .\"postListing\" == true }", "transition": "f1-upload-listing"}, {"condition": "${ .\"submitDoc\" == true }", "transition": "f2-upload-verification"}, {"condition": "${ .\"submitClientInfo\" == true }", "transition": "f3-upload-client"}], "defaultCondition": {"end": true}}}]}]
        # qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/<organization>/poliflow-test-applications/refund/sample-function
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: f2
  namespace: refund
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
        # qpoption.knative.dev/flow-config-allowed_json_flows: | 
        #   [{"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "data_based_switch_state", "value": {"name": "entry-decision", "type": "switch", "dataConditions": [{"condition": "${ .\"postListing\" == true }", "transition": "f1-upload-listing"}, {"condition": "${ .\"submitDoc\" == true }", "transition": "f2-upload-verification"}, {"condition": "${ .\"submitClientInfo\" == true }", "transition": "f3-upload-client"}], "defaultCondition": {"end": true}}}]}]
        # qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/<organization>/poliflow-test-applications/refund/sample-function
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: f3
  namespace: refund
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
        # qpoption.knative.dev/flow-config-allowed_json_flows: | 
        #   [{"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "data_based_switch_state", "value": {"name": "entry-decision", "type": "switch", "dataConditions": [{"condition": "${ .\"postListing\" == true }", "transition": "f1-upload-listing"}, {"condition": "${ .\"submitDoc\" == true }", "transition": "f2-upload-verification"}, {"condition": "${ .\"submitClientInfo\" == true }", "transition": "f3-upload-client"}], "defaultCondition": {"end": true}}}]}]
        # qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/<organization>/poliflow-test-applications/refund/sample-function
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: f4
  namespace: refund
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
        # qpoption.knative.dev/flow-config-allowed_json_flows: | 
        #   [{"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "data_based_switch_state", "value": {"name": "entry-decision", "type": "switch", "dataConditions": [{"condition": "${ .\"postListing\" == true }", "transition": "f1-upload-listing"}, {"condition": "${ .\"submitDoc\" == true }", "transition": "f2-upload-verification"}, {"condition": "${ .\"submitClientInfo\" == true }", "transition": "f3-upload-client"}], "defaultCondition": {"end": true}}}, {"type": "function:knative", "value": {"operation": "f1"}}, {"type": "event", "value": {"trigger": {"name": "uploadPhoto", "type": "photo.database.upload", "kind": "produced"}, "result": {"name": "newPhoto", "source": "database-dummy", "type": "photo.database.new", "kind": "consumed"}}}]}]
        # qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/<organization>/poliflow-test-applications/refund/sample-function
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: database-dummy
  namespace: refund
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
        # qpoption.knative.dev/flow-config-type: event
        # qpoption.knative.dev/flow-config-allowed_json_flows: | 
        #   [{"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "data_based_switch_state", "value": {"name": "entry-decision", "type": "switch", "dataConditions": [{"condition": "${ .\"postListing\" == true }", "transition": "f1-upload-listing"}, {"condition": "${ .\"submitDoc\" == true }", "transition": "f2-upload-verification"}, {"condition": "${ .\"submitClientInfo\" == true }", "transition": "f3-upload-client"}], "defaultCondition": {"end": true}}}, {"type": "function:knative", "value": {"operation": "f1"}}]}, {"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "data_based_switch_state", "value": {"name": "entry-decision", "type": "switch", "dataConditions": [{"condition": "${ .\"postListing\" == true }", "transition": "f1-upload-listing"}, {"condition": "${ .\"submitDoc\" == true }", "transition": "f2-upload-verification"}, {"condition": "${ .\"submitClientInfo\" == true }", "transition": "f3-upload-client"}], "defaultCondition": {"end": true}}}, {"type": "function:knative", "value": {"operation": "f1"}}, {"type": "event", "value": {"trigger": {"name": "uploadPhoto", "type": "photo.database.upload", "kind": "produced"}, "result": {"name": "newPhoto", "source": "database-dummy", "type": "photo.database.new", "kind": "consumed"}}}, {"type": "function:knative", "value": {"operation": "f4"}}, {"type": "function:knative", "value": {"operation": "f5"}}]}, {"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "data_based_switch_state", "value": {"name": "entry-decision", "type": "switch", "dataConditions": [{"condition": "${ .\"postListing\" == true }", "transition": "f1-upload-listing"}, {"condition": "${ .\"submitDoc\" == true }", "transition": "f2-upload-verification"}, {"condition": "${ .\"submitClientInfo\" == true }", "transition": "f3-upload-client"}], "defaultCondition": {"end": true}}}, {"type": "function:knative", "value": {"operation": "f1"}}, {"type": "event", "value": {"trigger": {"name": "uploadPhoto", "type": "photo.database.upload", "kind": "produced"}, "result": {"name": "newPhoto", "source": "database-dummy", "type": "photo.database.new", "kind": "consumed"}}}, {"type": "function:knative", "value": {"operation": "f4"}}, {"type": "function:knative", "value": {"operation": "f5"}}, {"type": "event", "value": {"trigger": {"name": "verification", "type": "info.database.verification", "kind": "produced"}, "result": {"name": "resultVerification", "source": "database-dummy", "type": "info.database.result", "kind": "consumed"}}}, {"type": "function:knative", "value": {"operation": "f7"}}, {"type": "function:knative", "value": {"operation": "f6"}}, {"type": "function:knative", "value": {"operation": "f8"}}]}, {"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "data_based_switch_state", "value": {"name": "entry-decision", "type": "switch", "dataConditions": [{"condition": "${ .\"postListing\" == true }", "transition": "f1-upload-listing"}, {"condition": "${ .\"submitDoc\" == true }", "transition": "f2-upload-verification"}, {"condition": "${ .\"submitClientInfo\" == true }", "transition": "f3-upload-client"}], "defaultCondition": {"end": true}}}, {"type": "function:knative", "value": {"operation": "f2"}}]}, {"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "data_based_switch_state", "value": {"name": "entry-decision", "type": "switch", "dataConditions": [{"condition": "${ .\"postListing\" == true }", "transition": "f1-upload-listing"}, {"condition": "${ .\"submitDoc\" == true }", "transition": "f2-upload-verification"}, {"condition": "${ .\"submitClientInfo\" == true }", "transition": "f3-upload-client"}], "defaultCondition": {"end": true}}}, {"type": "function:knative", "value": {"operation": "f3"}}]}]
        # qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/<organization>/poliflow-test-applications/refund/database-dummy
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: result
  namespace: refund
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
        # qpoption.knative.dev/flow-config-allowed_json_flows: | 
        #   [{"type": "sequence", "value": [{"type": "event", "value": {"name": "triggerEvent", "source": "entry-point", "type": "http.request.received", "kind": "consumed"}}, {"type": "function:expression", "value": null}, {"type": "function:knative", "value": {"operation": "f1"}}, {"type": "event", "value": {"trigger": {"name": "uploadPhoto", "type": "photo.database.upload", "kind": "produced"}, "result": {"name": "newPhoto", "source": "database-dummy", "type": "photo.database.new", "kind": "consumed"}}}, {"type": "function:knative", "value": {"operation": "f4"}}, {"type": "function:knative", "value": {"operation": "f5"}}, {"type": "event", "value": {"trigger": {"name": "verification", "type": "info.database.verification", "kind": "produced"}, "result": {"name": "resultVerification", "source": "database-dummy", "type": "info.database.result", "kind": "consumed"}}}, {"type": "function:knative", "value": {"operation": "f7"}}, {"type": "function:knative", "value": {"operation": "f6"}}, {"type": "function:knative", "value": {"operation": "f8"}}, {"type": "event", "value": {"trigger": {"name": "client", "type": "info.database.client", "kind": "produced"}, "result": {"name": "resultClient", "source": "database-dummy", "type": "info.database.resultClient", "kind": "consumed"}}}, {"type": "parallel", "value": [{"type": "sequence", "value": [{"type": "function:knative", "value": {"operation": "f9"}}]}, {"type": "sequence", "value": [{"type": "function:knative", "value": {"operation": "f10"}}]}, {"type": "sequence", "value": [{"type": "function:knative", "value": {"operation": "f11"}}]}]}, {"type": "function:expression", "value": null}]}]
        # qpoption.knative.dev/flow-activate: enable
    spec:
      containers:
        - image: ghcr.io/<organization>/poliflow-test-applications/refund/result
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  generation: 1
  name: bind-entry-point
  namespace: refund
spec:
  sink: 
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker
      namespace: refund
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: entry-point
    namespace: refund
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: database-dummy-trigger
  namespace: refund
spec:
  broker: broker
  filters:
    - any:
        - exact:
            type: order.database.get
        - exact:
            type: info.database.emitRefund
        - exact:
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: database-dummy
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: result-trigger
  namespace: refund
spec:
  broker: broker
  filters:
    - any:
        - exact:
            type: refund.workflow.finish
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: result
